src/hooks/useDocumentDriveServer.ts
src/hooks/useDocumentDrives.ts

Fixes #30.
All components that use the `useDocumentDrivesServer` hook were triggering a document drives fetch request, resulting in multiple parallel requests on startup.

Avoid double fetching of document drives on startup

---

src/hooks/useDrivesContainer.ts

- Cancel rename when new name is empty
**Note: ** this PR depends on https://github.com/powerhouse-inc/document-model-electron/pull/33

feat: cancel rename when new name is empty

---

package.json
yarn.lock

Update document-model lib to v1.0.29 (this version includes the support for UNDO operations)

Update document-model 1.0.29

---

src/utils/getSwitchboardUrl.ts

- Use`encodeURIComponent` instead `encodeURI` when encoding switchboard query

fix: properly encode switchboard query

---

.env
.gitignore
src/env.d.ts
src/hooks/useFeatureFlags/default-config.ts
src/store/document-model.ts
tsconfig.json

Makes available editors configurable with environment variables on build time.
Disable document drive by default as we don't support it as a normal document.

Feat env editors

---

package.json
src/components/editors.tsx
src/globals.d.ts
src/renderer.ts
src/utils/document-editor-debug-tools.ts
yarn.lock

- Added `documentEditorDebugTools` object
> Usage:
> `window.documentEditorDebugTools.operationsTable()`: renders document's operations in a table format
> `window.documentEditorDebugTools.scopeOperationsTable(scope: string)`: filters document's operations by the scope provided and renders the result in a table format
> `window.documentEditorDebugTools.operationsLog()`: renders all the operations dispatched for the current editor session (all dispatched operations are recorded, no matter if they were added or not to the document)
> `window.documentEditorDebugTools.operationsLogTable()`: same as previous method but in table format
> `window.documentEditorDebugTools.getDocument()`: returns the document object.
Consider that this dev tools and the document are only available when the editor …

feat: added editor debug tools

---

src/components/editors.tsx
src/hooks/useDocumentDriveServer.ts
src/pages/content.tsx
src/store/document-drive.ts

Ignores the resulting document when storing an operation from the editor.
Also added a debounce so that operations done quickly after each other are grouped into a single `addOperations` call.

Allow dispatching simultaneous operations

---

src/hooks/useFeatureFlags/useFeatureFlags.ts

- use default values if there is a missing key for feature flags

feat: use default values if there is a missing key for feature flags

---

src/hooks/useDrivesContainer.ts

- Add a `visited` parameter to keep track of the nodes that are being visited.
- Before recursing, check if the current node is already in the visited set. If it is, throw an error indicating a circular reference.
- Add the current node to the visited set before making the recursive call.

feat: detect circular reference in node path

---

src/hooks/useDocumentDriveServer.ts

we check and return if src id equals target id when doing a copy node. should do the same thing for move.

feat: also do src equals target check in move function

---

src/components/modal/modals/CreateDocumentModal.tsx
src/hooks/useDocumentDriveServer.ts
src/pages/content.tsx

currently we do not allow linking directly to files, only drives and directories. I have here minimal changes to allow linking to files as well. I do not know why this feature was not initially set up in this way, so I hope my changes are not going to introduce new bugs. 
Please take a look and let me know if there is other logic that this code affects that I did not see. There could also be side effects I am not aware of.

feat: allow url for file

---

src/pages/content.tsx

the existing logic for opening files from the url made the assumption that files with no parent folder, i.e. ones directly in the drive, would always have `null` for the `parentFolder` property. However, there is logic in the document drive code that sets this value to `""` instead. This causes the url logic to break.
To fix this for now, I have updated the url logic to treat falsy values for `parentFolder` as meaning the parent is the drive. However, in my opinion it would be better to refactor the code to always use `null` only, since that is more predictable.

feat: fix load file from url

---

package-lock.json
package.json
src/components/editors.tsx
src/components/history.ts
src/hooks/useDrivesContainer.ts
src/hooks/useOnDropEvent.ts

- `parentFolder` property was added to the `TreeItem` type in the design system. Now set that value in the `driveToBaseItems` function so that it can be used in the app
- when attempting to move an item, make sure that we are not trying to move it into the folder it is already in. This happens when you drag an item and then change your mind and drop it. This is the cause of the accidental rename bug.

feat: fix drag and drop accidental rename

---

src/utils/file.ts

Ignores error when user cancels the file picker when exporting a document.
https://powerhouse-u6.sentry.io/issues/5223398848/events/4a4719001b064af8aca64eb6f6444ebc/

feat: ignore AbortError when user cancels file picker

---

package-lock.json
src/app/document-drive.ts
src/app/sentry.ts
src/components/editors.tsx
src/components/modal/modals/SettingsModal.tsx
src/components/root.tsx
src/components/sidebar.tsx
src/hooks/useClientErrorHandler.ts
src/hooks/useConnectCrypto.ts
src/hooks/useDocumentDriveServer.ts
src/hooks/useDocumentDrives.ts
src/hooks/useLoadDefaultDrives.ts
src/hooks/useLogin.ts
src/hooks/useOpenFile.tsx
src/renderer.ts
src/services/logger.ts
src/services/renown/index.ts
src/store/user.ts
src/utils/browser-document-drive.ts
src/utils/document-model.ts
src/utils/file.ts

Sentry was only getting error that are not caught and reach the ErrorBoundary component.
I've changed the `console.error` calls to also report to Sentry.
Errors from the document-drive lib will be also sent.
This will probably generate too many errors, we can start ignoring some of them as we understand which are meaningful to report or not.

feat: log catched errors to sentry

---

src/components/editors.tsx
src/components/file-content-view.tsx
src/components/folder-view.tsx
src/hooks/useDocumentDriveServer.ts
src/hooks/useUiNodes.ts
src/pages/content.tsx
src/store/document-drive.ts

We need to make sure that a given node is in fact a file node before we attempt to open it as a document.
I have added checks to do this in the `useFileNodeDocument` hook. Since this logic is inextricably linked to the nodes, I have moved the invocation of this hook into the `useUiNodes` hook. This way, we can also get the document data from the same hook for convenience. This also prevents possible confusion.
I have also renamed the `addOperation` function exported by `useFileNodeDocument` to avoid confusion with the `addOperation` function exported by `useDocumentDriveServer`.

feat: only open document when we know node is file

---

src/utils/registerServiceWorker.ts

- use `routerBasename` to get service worker script path

fix: use routerBasename to get service worker script path

---

CHANGELOG.md
package.json
src/utils/reactor.ts
src/vite-env.d.ts

- Preserve all remote drives if no default drives config is passed

feat: Preserve all remote drives if no default drives config is passed

---

package-lock.json
package.json
src/components/app.tsx
src/components/footer.tsx
src/i18n/locales/en.json

- Added `Footer` component integration
> NOTE: this PR requires https://github.com/powerhouse-inc/design-system/pull/366

feat: Footer component integration

---

package-lock.json
package.json
src/utils/reactor.ts

- Change `removeOldRemoteDrives` strategy to `preserve-by-url-and-detach`
> NOTE: This PR requires https://github.com/powerhouse-inc/document-drive/pull/305

feat: added detach strategy for old drives

---

studio/index.ts
studio/vite-plugin.ts
vite.renderer.config.mts

When building Connect, `rollupOptions.external` is used to prevent react imports to be resolved by vite.
Studio uses Vite Dev Server which is very aggressive at pre-bundling dependencies and uses `esbuild` instead of `rollup`.
It changes all `import from "react"` into `import from "/@id/react"`. Since vite doesn't provide a method to do this on the dev server, this uses a proposed plugin to revert that import change.
https://github.com/vitejs/vite/issues/6393#issuecomment-1006819717

fix: use single instance of react dependencies on studio mode

---

studio/helpers.ts
studio/server.ts

MacOS and Linux: No changes
in Windows:
if running connect from git bash or something similar, the app follows the normal flow (runs vite-envs.sh to define the env variables)
if running in PowerShell or something similar, the flow is executed as follow (before start the dev server):
- creates a backup of the `index.html`
- updates the `index.html` by removing default base64 values for LOCAL_DOCUMENT_MODELS and LOCAL_DOCUMENT_EDITORS in `envWithValuesInBase64` object (this forces the devServer to take the values from process.env)
- starts the dev server
the backup file is restored before running the vite-envs.sh, this allows windows users to change between powershell and bash compatible command lines

feat: force usage of env variables when vite-envs.sh execution fails

---

src/components/editors.tsx

- Since we are using `getEditor` to match a valid editor for the document type, there's no need to do this check again. This was keeping the `isLoadingEditor = true` for the json editor (because this second check doesn't match '*' with the document type)

fix(connect): removed duplicated editor check
