package.json, src/app/document-drive.ts, src/components/root.tsx, src/components/sidebar.tsx, src/components/tabs/tab-new.tsx, src/hooks/useDocumentDrive.ts, src/hooks/useDropFile.tsx, src/hooks/useOpenFile.tsx, src/hooks/utils.ts, src/main.ts, src/preload.ts, src/store/document-model.tsx, src/store/theme.ts, src/utils/file.ts, yarn.lock
https://github.com/powerhouse-inc/document-model-electron/assets/5501872/f54b99ff-7bf7-435a-a989-d4d133188f34
=> WIP: Design system navigation components and Electron Document Drive

package.json, src/app/document-drive.ts, src/components/drive-container.tsx, src/components/sidebar.tsx, src/hooks/useDocumentDrive.ts, src/preload.ts, src/services/document-drive/electron-document-drive.ts, src/services/document-drive/index.ts, src/store/index.ts, src/utils/index.ts, src/utils/path.ts, yarn.lock
- Implemented copy and move folder (inside drive)
**NOTE: This PR requires new version of [design-system](https://github.com/powerhouse-inc/design-system) from this [PR](https://github.com/powerhouse-inc/design-system/pull/82)**
=> feat: implemented copy and move folder (inside drive)

package.json, src/app/document-drive.ts, src/components/drive-container.tsx, src/components/sidebar.tsx, src/components/tabs/tab-new.tsx, src/hooks/useDocumentDrive.ts, src/hooks/useDropFile.tsx, src/main.ts, src/preload.ts, src/services/document-drive/electron-document-drive.ts, src/services/document-drive/index.ts, src/store/index.ts, src/utils/index.ts, src/utils/path.ts, vite.main.config.mjs, yarn.lock
Fixes #7 
Document drive changes are stored inside the app folder.
https://github.com/acaldas/document-model-electron/assets/5501872/5809bacd-a75c-43b5-846f-91927e12ac58
=> Add support for create new folder and rename node

src/app/document-drive.ts, src/components/drive-container.tsx, src/hooks/useDocumentDrive.ts, src/index.css, src/preload.ts, src/services/document-drive/electron-document-drive.ts, src/services/document-drive/index.ts
- Added sort nodes
- Fix input styles
- Abort folder creation with empty name
=> feat: Added sort nodes

package.json, src/components/drive-container.tsx, src/components/folder-view.tsx, src/components/root.tsx, src/hooks/useDrivesContainer.ts, src/pages/content.tsx, src/store/document-drive.ts, yarn.lock
- Added `ItemsContext` integration
**Note: This PR depends on https://github.com/powerhouse-inc/design-system/pull/103**
=> feat: 🚀 Added ItemsContext integration

package.json, src/components/drive-container.tsx, src/components/modal/modals/DeleteItemModal.tsx, src/components/modal/modals/UpgradeDriveModal.tsx, src/hooks/useDocumentDriveServer.ts, src/hooks/useDrivesContainer.ts, src/pages/content.tsx, yarn.lock
- Enable rename option when copy or move a folder with a name already taken
**NOTE:** this PR depends on https://github.com/powerhouse-inc/document-model-electron/pull/31 and https://github.com/powerhouse-inc/design-system/pull/113
=> Enable rename option when copy or move a folder with a name already taken

package.json, src/app/document-drive.ts, src/components/folder-view.tsx, src/hooks/useDocumentDriveServer.ts, src/pages/content.tsx, src/preload.ts, yarn.lock
Fixes https://github.com/powerhouse-inc/document-drive/issues/6
Fixes #37.
Updated code with newest version of `document-drive`. Now documents are actually copied.
=> Copies document when file node is copied to another folder

package.json, src/app/document-drive.ts, src/hooks/useDocumentDriveServer.ts, src/hooks/useDocumentDrives.ts, src/preload.ts, src/utils/browser-document-drive.ts, vite.renderer.config.ts, yarn.lock
Fixes #39 
If the Electron API is not defined then falls back to the browser implementation
=> Added support for browser document drive

package.json, src/components/content/index.ts, src/components/content/section.tsx, src/components/folder-view.tsx, src/components/search-bar.tsx, src/hooks/index.ts, src/hooks/useGetReadableItemPath.ts, src/i18n/locales/en.json, src/pages/content.tsx, yarn.lock
- Implemented base folder-view design
Note: This PR depends on https://github.com/powerhouse-inc/design-system/pull/128
=> feat: 🚀 Implemented base folder-view design

src/components/folder-view.tsx, src/hooks/useDrivesContainer.ts, src/hooks/useGetReadableItemPath.ts, src/pages/content.tsx
- fix folder selection in folder view + files path
=> fix: folder selection in folder view + Files path

.eslintignore, .prettierignore, package.json, scripts/index.js
- Added  prepare scripts.
- Added copy `icons.svg` into `public` folder after every dependency install
=> feat: added prepare script

package.json, src/components/folder-view.tsx, yarn.lock
- added support for delete option in `FolderItem` and `FileItem`
Note: This PR requires https://github.com/powerhouse-inc/design-system/pull/135
=> feat: added support for delete option in FolderItem and FileItem

src/components/drive-container.tsx, src/pages/content.tsx, src/store/document-drive.ts
- auto-select first drive if there's no selected path
=> feat: auto-select first drive if there's no selected path

src/components/folder-item/folder-item.tsx, src/components/folder-item/index.ts, src/components/folder-view.tsx, src/hooks/useDrivesContainer.ts, src/hooks/useFolderContent.ts, src/pages/content.tsx
- enabled rename option for folders in folder view
NOTE: This PR depends on https://github.com/powerhouse-inc/design-system/pull/138
=> feat: enabled rename option for folders in folder view

src/pages/content.tsx
- Rename document drive node when document model name is changed
=> feat: rename document drive node when document model name is changed

package.json, src/components/editors.tsx, src/utils/document-model.ts, yarn.lock
- Fix document data removed after changing global schema
> **NOTE:** This PR depends on https://github.com/powerhouse-inc/document-model-electron/pull/67
=> Fix document data removed after changing global schema

package.json, src/hooks/useDocumentDriveServer.ts, yarn.lock
- added support for document in addfile action
> NOTE: This PR requires https://github.com/powerhouse-inc/document-model-libs/pull/57
=> feat: added support for document in addfile action

package.json, src/index.css, src/pages/content.tsx, yarn.lock
=> feat: enabled rwa editor

src/components/editors.tsx
- enabled undo/redo with new document structure
=> feat: enabled undo/redo with new document structure

src/components/folder-view.tsx, src/hooks/useDocumentDriveById.ts, src/hooks/useGetDocumentById.ts, src/i18n/locales/en.json, src/preload.ts, src/utils/getSwitchboardUrl.ts, src/utils/join.ts, src/utils/openUrl.ts
- added switchboard link to document files
=> feat: added switchboard link to document files

src/hooks/useFeatureFlags/default-config.ts, src/utils/getSwitchboardUrl.ts
- fix rwa document name
> NOTE: this PR depends on https://github.com/powerhouse-inc/document-model-libs/pull/78
=> feat: fix rwa document name

package.json, pnpm-lock.yaml, src/hooks/useDrivesContainer.ts
- Enabled add cloud drive modal
=> feat: enabled add cloud drive modal

src/components/drive-container.tsx, src/utils/browser-document-drive.ts
Also fixes local drive on browser
=> feat: add pull trigger on cloud drives

package.json, pnpm-lock.yaml, src/components/editors.tsx, src/store/editor.ts
- Enabled editor controls
> NOTE: This PR depends on https://github.com/powerhouse-inc/document-model-libs/pull/80 and https://github.com/powerhouse-inc/design-system/pull/206
=> feat: enabled editor controls

src/utils/getSwitchboardUrl.ts
=> feat: updated rwa query

src/hooks/useDocumentDriveServer.ts, src/store/document-drive.ts, src/utils/document-model.ts
https://github.com/powerhouse-inc/document-model-electron/assets/5501872/7a21af81-a73c-4c5a-93ac-b17f943d8848
=> feat: update editor when opened document is changed

package.json, pnpm-lock.yaml, src/components/file-item/file-item.tsx, src/components/file-item/index.ts, src/components/folder-view.tsx, src/components/modal/modals/CreateDocumentModal.tsx, src/components/modal/modals/index.ts, src/i18n/locales/en.json, src/pages/content.tsx
- Added support for create document name modal
- Added support for rename file items
> NOTE: this PR requires https://github.com/powerhouse-inc/design-system/pull/210
=> feat: added support for rename files + create file name modal

package.json, src/preload.ts, yarn.lock
Fixes initial sync status for empty drive
=> feat: fix sync status

package.json, src/components/editors.tsx, src/components/file-item/file-item.tsx, src/hooks/useOpenSwitchboardLink.ts, src/pages/content.tsx, yarn.lock
- enabled switchboard link in RWA editor
> NOTE: This PR requires https://github.com/powerhouse-inc/document-model-libs/pull/82
=> feat: enabled switchboard link in RWA editor

package.json, src/app/document-drive.ts, src/components/modal/modals/ConfirmationModal.tsx, src/components/modal/modals/SettingsModal.tsx, src/components/modal/modals/index.ts, src/components/sidebar.tsx, src/hooks/useDocumentDriveServer.ts, src/hooks/useFeatureFlags/useFeatureFlags.ts, src/i18n/locales/en.json, src/preload.ts, yarn.lock
- added clear storage setting
- added enable/disable document types
=> feat: added connect settings

package.json, src/hooks/useConnectCrypto.ts, src/main.ts, src/preload.ts, src/services/crypto/browser.ts, src/services/crypto/index.ts, yarn.lock
Connects generates an identifier in the format of `did:key:zDnaeV7o3uvn6cxSAeThDmdb2p1uhUPpCMsM3D1b5mPDTrCYf`.
This is a format compatible with DIDs which means that Connect is the holder of the represented public key.
https://didlint.ownyourdata.eu/validate?did=did:key:zDnaeV7o3uvn6cxSAeThDmdb2p1uhUPpCMsM3D1b5mPDTrCYf
The DID document generated from that identifier:
```
{
"@context": [
"https://www.w3.org/ns/did/v1",
{
"EcdsaSecp256r1VerificationKey2019": "https://w3id.org/security#EcdsaSecp256r1VerificationKey2019",
"publicKeyJwk": {
"@id": "https://w3id.org/security#publicKeyJwk",
"@type": "@json"
}
}
],
"id": "did:key:zDnaeV7o3uvn6cxSAeThDmdb2p1uhUPpCMsM3D1b5mPDTrCYf",
"verificationMethod": [
{
"id": "did:key:zDnaeV7o3uvn6cxSAeThDmdb2p1uhUPpCMsM3D1b5mPDTrCYf#zDnaeV7o3uvn6cxSAeThDmdb2p1 …
```
=> Generate did:key

src/i18n/locales/en.json
=> fix: settings modal typo

package.json, yarn.lock
bump libs to enable transactions editor 🚀
=> feat: add transactions editor

package.json, src/components/file-item/file-item.tsx, src/components/folder-item/folder-item.tsx, src/components/modal/modals/DeleteDriveModal.tsx, src/components/modal/modals/DeleteItemModal.tsx, src/components/modal/modals/index.ts, src/hooks/useDrivesContainer.ts, src/i18n/locales/en.json, yarn.lock
- Added DeleteDrive Modal
- Enabled Delete File modal confirmation
> NOTE: This PR requires https://github.com/powerhouse-inc/design-system/pull/235
=> feat: added delete drive modal + enable delete file modal confirmation

package.json, src/components/drive-container.tsx, src/components/file-item/file-item.tsx, src/components/folder-item/folder-item.tsx, src/components/folder-view.tsx, src/hooks/useOnDropEvent.ts, yarn.lock
- enabled drop target for FolderItem
- drop file into FolderItem
- drop folder into FolderItem
- drop and copy folder into FolderItem
- drop file into FolderItem
- drop and copy file into FolderItem
> NOTE: This PR requires https://github.com/powerhouse-inc/design-system/pull/237
=> feat: enabled drop target for FolderItem

package.json, src/components/root.tsx, src/components/sidebar.tsx, src/hooks/useEnsInfo.ts, src/services/viem.ts, yarn.lock
=> feat: fetch user's ens info

package.json, yarn.lock
=> feat: bump libs

src/index.css
=> feat: fix css import order

.env, src/components/modal/modals/SettingsModal.tsx, src/env.d.ts, src/hooks/useFeatureFlags/default-config.ts, src/hooks/useLoadDefaultDrive.ts, src/hooks/useLoadInitialData.ts
- Add default drive on load app.
=> feat: load default drive

package.json, src/components/editors.tsx, src/index.css, yarn.lock
- Use scoped styles for document-model-libs editors
https://discord.com/channels/815917281728659516/1171481967242518620/1220377481727447040
> NOTE: This PR requires https://github.com/powerhouse-inc/document-model-libs/pull/108
=> feat: fix tailwind class conflicts

package.json, src/hooks/useDrivesContainer.ts, src/hooks/useLoadInitialData.ts, src/hooks/useNavigateToItemId.ts, src/pages/content.tsx, yarn.lock
- expand selected path in sidebar on initial path load
> NOTE: This PR requires https://github.com/powerhouse-inc/design-system/pull/249
=> feat: expand selected path in sidebar on initial path load

.env, connect.config.ts, src/components/drive-container.tsx, src/env.d.ts, src/hooks/useFeatureFlags/default-config.ts, src/utils/drive-sections.ts
- Show/Hide a drive section from `connect.config`
- Added docs for env var values
- Migrated drives config from `feature flags` to `connect.config`
- Refactor `DrivesSections`
=> feat: added config to hide drive sections

forge.config.ts, package.json, src/app/deeplink.ts, yarn.lock
- removed `electron-deeplink` pkg
=> feat: removed electron-deeplink pkg and updated deep links

.env, connect.config.ts, src/env.d.ts, src/hooks/useConnectConfig.ts, src/pages/content.tsx, src/utils/drive-sections.ts, tsconfig.json, vite.main.config.ts, vite.renderer.config.ts
- hide `SearchBar` from config file
=> feat: hide searchbar from config

package.json, src/components/sidebar.tsx, yarn.lock
- replaced sidebar input header by connect logo
> NOTE: This PR requires https://github.com/powerhouse-inc/design-system/pull/252
=> feat: replaced sidebar input header by connect logo

vercel.json
- added rewrite rules to `vercel.json` config
=> feat: added rewrite rules to vercel.json config

package-lock.json, package.json, src/components/modal/modals/ConfirmationModal.tsx, src/i18n/locales/en.json, src/pages/content.tsx, src/utils/validate-document.ts
- added modal confirmation when export document with errors
=> feat: added modal confirmation when export document with errors

src/hooks/useDocumentDriveServer.ts, src/hooks/useDocumentDrives.ts, src/hooks/useLoadInitialData.ts, src/utils/document-drive-server.ts
- subscribe to server updates when load initial data
=> fix: subscribe to server updates when load initial data

package-lock.json, package.json
integrate new changes from deps
=> feat: bump libs 2024 04 09

src/main.ts
disable dev tools when app is packaged. 
see here for [reference](https://github.com/electron/electron/issues/6879#issuecomment-932242861).
=> feat: disable dev tools in production

.eslintrc.json, package-lock.json, package.json, src/hooks/useFeatureFlags/atom.ts, src/services/storage/browser.ts, src/store/index.ts, src/store/utils.ts, src/utils/browser-document-drive.ts
Depends on https://github.com/powerhouse-inc/document-drive/pull/130
Fixes https://github.com/powerhouse-inc/switchboard-boilerplate/issues/130
=> feat: separate browser storage

src/hooks/useDocumentDriveServer.ts
remove allow list check from add remote drive function.
=> feat: remove check

src/hooks/useIsAllowedToCreateDocuments.ts
Add checks for empty string or wrong formatted string in env var for allow list.
=> feat: allow empty string allow list

src/utils/document-model.ts
-  re-enable onErrorCallback with new operations error prop
=> feat: re-enable onErrorCallback with new operations error prop

package-lock.json, package.json
bump design system to integrate QA updates.
=> feat: integrate QA updates

package-lock.json, package.json
=> feat: bump libs 2024 05 08

package-lock.json, package.json
=> feat: update experimental deps

package-lock.json, package.json
- updated `document-drive` lib (this ver includes fix for duplicated operations and support for new `id` operation prop)
https://github.com/powerhouse-inc/document-model-electron/assets/20387722/f2ff1b27-d7b9-4fa3-a6b9-783b819aabe3
=> feat: updated document-drive ver

src/components/login.tsx
-  fix `Authorize Connect` font color
=> feat: fix Authorize Connect font color

package-lock.json, package.json, src/utils/file.ts
- Added `downloadFile` fallback for brave
=> feat: downloadFile fallback

src/hooks/useLoadInitialData.ts
- show success sync toast only after recover from error sync
=> feat: show success sync toast only after recover from error sync

src/pages/content.tsx
- use setTimeout as fallback for requestIdleCallback (fix safari)
=> feat: use setTimeout as fallback for requestIdleCallback

src/pages/content.tsx
=> feat: remove hello from content

package-lock.json, package.json, src/components/drive-container.tsx, src/components/file-item/file-item.tsx, src/components/folder-item/folder-item.tsx, src/hooks/useDocumentDriveServer.ts, src/hooks/useDrivesContainer.ts
- Enabled sync icons per file/folder
=> feat: enabled sync icons for folders and files

.github/workflows/e2e-dev.yml, cypress.config.ts, cypress/e2e/navigation.cy.ts, cypress/e2e/utils/index.ts, cypress/fixtures/example.json, cypress/support/commands.ts, cypress/support/e2e.ts, cypress/tsconfig.json, package-lock.json, package.json
=> 339 update cypress setup for connect webapp

package-lock.json, package.json, src/components/file-content-view.tsx, src/components/folder-view.tsx
- added virtualization for files item
> 500 > files = 20ms 〜
=> feat: added virtualization for files content

package-lock.json, package.json, src/components/editors.tsx, src/pages/content.tsx
bump libs to integrate revision history
=> feat: integrate revision history

package-lock.json, src/components/folder-item/folder-item.tsx, src/components/folder-view.tsx, src/pages/content.tsx
- disable sync icon for local folders
=> feat: disable sync icon for local folders

package-lock.json, package.json, src/components/editors.tsx, src/hooks/useConnectCrypto.ts, src/pages/content.tsx, src/services/crypto/index.ts, src/utils/document-model.ts
=> Signature implementation

src/utils/getSwitchboardUrl.ts
=> feat: update query

package-lock.json, package.json, src/components/file-content-view.tsx, src/hooks/useWindowSize.ts
- replaced react-window by tanstack/react-virtual
=> fix: rename files not working

src/components/folder-view.tsx, src/hooks/useDrivesContainer.ts, src/utils/index.ts, src/utils/tree-items.ts
- sort folders and files alphabetically
=> feat: sort folders and files alphabetically

package-lock.json, package.json, src/app/document-drive.ts, src/hooks/useClientErrorHandler.ts, src/hooks/useDocumentDriveServer.ts, src/hooks/useDocumentDrives.ts, src/hooks/useDrivesContainer.ts, src/hooks/useLoadInitialData.tsx, src/preload.ts, src/utils/drive-sections.ts
- register new pullResponderTrigger when the current one is not longer valid
> This PR requires https://github.com/powerhouse-inc/document-drive/pull/229
=> feat: register new pullResponderTrigger when the current one is not longer valid

src/hooks/useClientErrorHandler.ts
-  Handle invalid listener id with status error 400 instead of 404
=> feat: handle invalid listener id with status error 400 instead of 404

src/hooks/useLoadDefaultDrives.ts
- Reload default drives when config has been updated
=> feat: reload default drives when config has been updated

cypress.config.ts, cypress/e2e/navigation.cy.ts, cypress/e2e/utils/index.ts, src/components/ph-logo.tsx, src/components/sidebar.tsx, src/pages/content.tsx
=> feat: added base e2e tests

src/hooks/useDropFile.tsx, src/hooks/useOnDropEvent.ts
- Removed file extension when importing a document file
=> feat: removed file extension when importing a document file

src/hooks/useLoadInitialData.tsx
- fix merge conflict when adding a new pullResponder
Resolves powerhouse-inc/document-drive#239
=> feat: fix merge conflict when adding a new pullResponder

src/hooks/useLoadInitialData.tsx, src/hooks/utils.ts
=> fix: fix urlBranchMap

src/hooks/useLoadInitialData.tsx, src/hooks/utils.ts
=> fix: urlBranchMap

.env, package-lock.json, public/service-worker.js, src/components/modal/modals/DebugSettingsModal.tsx, src/renderer.ts, src/utils/registerServiceWorker.ts, vite.renderer.config.mts
- added browser refresh when a new version of connect is deployed
=> feat: added browser refresh when a new version of connect is deployed

package-lock.json, package.json
- update design-system and document-model-libs ver
> NOTE: This PR requires: https://github.com/powerhouse-inc/document-model-libs/pull/202
=> feat: update design-system and document-model-libs ver

src/hooks/useUiNodes.ts
- remove file ext when importing document
=> fix: remove file ext when importing document

.github/workflows/e2e-dev.yml, cypress.config.ts, cypress/e2e/navigation.cy.ts, cypress/e2e/utils/index.ts
- Fix broken e2e tests
- changed github action to run on pull requests to other branches
=> feat: setup connect tests on pull requests to other branches

package-lock.json, package.json, src/hooks/useDocumentDriveServer.ts
-  handle syncUnitStatus not found error
> NOTE: this PR requires https://github.com/powerhouse-inc/document-drive/pull/292
=> feat: handle syncUnitStatus not found error

.env
- fix env values for makerdao prod
=> fix: env values makerdao prod

package-lock.json, package.json, src/components/footer.tsx, src/components/modal/modals/DisclaimerModal.tsx, src/components/modal/modals/index.ts, src/i18n/locales/en.json
- added disclaimer update to connect footer
=> feat: added disclaimer update to connect footer

src/components/footer.tsx
update cookie link url to be https://fusion.sky.money/cookies-policy
=> feat: update cookie policy link

src/components/app-loader.tsx, src/components/app.tsx, src/index.ts, src/renderer.ts
=> fix: double render in studio mode

package.json, studio/helpers.ts, studio/server.ts, studio/vite-plugin.ts
=> Enforce minimum node version and debounce studio reload

package-lock.json, package.json, src/components/editors.tsx, src/utils/getSwitchboardUrl.ts
- enable switchboard link in document toolbar
=> feat(connect): enable switchboard link in document toolbar

package-lock.json, src/store/document-drive.ts
Fixes https://github.com/powerhouse-inc/connect/issues/614
=> fix: updates editor when opened document receives a new strand

src/hooks/useDocumentDriveServer.ts, src/utils/document-model.ts
`reactor.on('strandUpdate')` was not being unsubscribed after resolving so it was breaking the upload loop.
=> fix: improved upload of large documents

package-lock.json, package.json, studio/index.ts
- update dynamic loading packages
=> feat: update dynamic loading packages

studio/index.ts, studio/server.ts
=> feat: fix load empty packages

studio/index.ts, studio/server.ts
- enabled open option for studio
=> Add open option

studio/index.ts
=> feat: enable packages option
